# Numpy

### Numpy Array

In [1]:
# 리스트와 넘파이 어레이 속도 비교
import numpy as np
np_arr = np.arange(100000)
nu_list = [i for i in range(100000)]

In [2]:
%%time
for i in range(100):
    sum(nu_list)

Wall time: 151 ms


In [3]:
%%time
for i in range(100):
    np.sum(np_arr)

Wall time: 5 ms


### 1차원 배열 만들기

In [4]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
type(ar)

numpy.ndarray

In [6]:
ar.shape

(10,)

### 벡터화 연산

In [7]:
al = [2 * i for i in range(10)]
al

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [8]:
2 * ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
2 * al

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [10]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [11]:
2 * a + b

array([12, 24, 36])

In [12]:
a == 2

array([False,  True, False])

In [13]:
b > 15

array([False,  True,  True])

In [14]:
(a == 2) & (b > 10)

array([False,  True, False])

### 2차원 배열

In [15]:
c = np.array([[0, 1, 2], [3, 4, 5]]) # 2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
c.shape

(2, 3)

In [17]:
len(c), len(c[0])

(2, 3)

In [18]:
d = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

In [19]:
d

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### 3차원 배열

In [20]:
e = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])

In [21]:
e.shape, e.ndim

((2, 3, 4), 3)

### 인덱싱

In [22]:
a = np.array([0, 1, 2, 3, 4])
a[2]

2

In [23]:
a[-1]

4

In [24]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a[0, 1]

1

### 배열 슬라이싱

In [25]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [26]:
a[0, :]

array([0, 1, 2, 3])

In [27]:
a[:, 1]

array([1, 5])

In [28]:
a[:2, :2]

array([[0, 1],
       [4, 5]])

In [29]:
m = np.array([[0, 1, 2, 3, 4],
             [5, 6, 7, 8, 9],
             [10, 11, 12, 13, 14]])
m[1, 2], m[-1, -1], m[1, 1:3], m[1:, 2], m[:2, 3:]

(7,
 14,
 array([6, 7]),
 array([ 7, 12]),
 array([[3, 4],
        [8, 9]]))

### 배열 인덱싱

In [30]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [31]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [32]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [33]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [34]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [36]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [37]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
x[x % 3 == 0], x[x % 4 == 1], x[(x % 3 == 0) & (x % 4 == 1)]

(array([ 3,  6,  9, 12, 15, 18]), array([ 1,  5,  9, 13, 17]), array([9]))