# 난수 발생과 카운팅

In [1]:
import numpy as np

### 시드 설정하기

In [2]:
np.random.rand(5)

array([0.27018428, 0.78676787, 0.93836444, 0.0174139 , 0.78404922])

In [3]:
np.random.rand(5)

array([0.65271206, 0.99726883, 0.83230082, 0.13428979, 0.79695162])

In [4]:
np.random.seed(2020)
np.random.rand(5)

array([0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873])

In [5]:
np.random.seed(2020)
np.random.rand(5)

array([0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873])

### 데이터의 순서 바꾸기

In [6]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.random.shuffle(x)
x

array([5, 7, 6, 4, 3, 1, 2, 8, 9, 0])

### 데이터 샘플링

In [8]:
np.random.choice(5, 5, replace=False) # shuffle과 같음

array([4, 0, 1, 2, 3])

In [9]:
np.random.choice(5, 5, replace=True) # 복원추출

array([4, 4, 0, 4, 1])

In [10]:
np.random.choice(5, 3, replace=False)

array([2, 0, 4])

In [11]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]) # 선택 확률을 다르게 하여 추출

array([0, 3, 3, 2, 2, 2, 3, 2, 3, 2])

### 난수 생성

In [12]:
np.random.rand(5)

array([0.04298562, 0.81831177, 0.70022645, 0.71843269, 0.72543355])

In [13]:
np.random.randn(5) # 표준정규분포에서 추출

array([-0.15583399,  1.3929476 ,  0.4957971 , -0.18760574, -0.97232061])

In [14]:
np.random.randint(10, size=10)

array([3, 3, 0, 0, 4, 6, 6, 8, 9, 9])

In [15]:
np.random.randint(10, 20, size=10)

array([19, 15, 11, 19, 10, 11, 17, 15, 10, 17])

In [16]:
prices = []
price = 10000
for i in range(250):
    tmp = price * (1 + np.random.randn(1)/100.)
    price = tmp[0]
    prices.append(price)
prices[:10]

[9986.168809624893,
 9994.699368314263,
 9934.753243634817,
 9898.326160077766,
 10083.766115457644,
 10205.432461802875,
 10285.54470902073,
 10125.398244344475,
 10413.879561195761,
 10468.618970587278]

### 정수 데이터 카운팅

In [17]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [18]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [19]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [20]:
count

array([2, 2, 1], dtype=int64)

In [21]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6)

array([0, 2, 3, 1, 0, 0], dtype=int64)

In [22]:
np.random.randint(2, size=10)

array([0, 0, 1, 1, 0, 0, 1, 0, 1, 1])

In [23]:
dice = np.random.randint(1, 7, size=100)
dice.mean()

3.46