# 난수 발생과 카운팅

In [1]:
import numpy as np

### 시드 설정하기

In [2]:
np.random.rand(5)

array([0.92999495, 0.36286364, 0.12360597, 0.36118384, 0.60761865])

In [3]:
np.random.rand(5)

array([0.77182963, 0.89077987, 0.44827606, 0.59284074, 0.14994574])

In [4]:
np.random.seed(2020)
np.random.rand(5)

array([0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873])

In [5]:
np.random.seed(2020)
np.random.rand(5)

array([0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873])

### 데이터의 순서 바꾸기

In [7]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.random.shuffle(x)
x

array([5, 7, 6, 4, 3, 1, 2, 8, 9, 0])

### 데이터 샘플링

In [11]:
np.random.choice(5, 5, replace=False) # shuffle과 같음

array([0, 2, 3, 1, 4])

In [12]:
np.random.choice(5, 5, replace=True) # 복원추출

array([2, 1, 2, 4, 4])

In [13]:
np.random.choice(5, 3, replace=False)

array([4, 1, 0])

In [16]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]) # 선택 확률을 다르게 하여 추출

array([2, 0, 3, 3, 3, 3, 3, 3, 2, 3])

### 난수 생성

In [17]:
np.random.rand(5)

array([0.44467178, 0.11104748, 0.53702586, 0.32579935, 0.86519536])

In [18]:
np.random.randn(5) # 표준정규분포에서 추출

array([-0.33764227, -0.12044229,  1.27944955, -0.49866644,  1.04592685])

In [20]:
np.random.randint(10, size=10)

array([1, 9, 0, 1, 7, 5, 0, 7, 1, 3])

In [21]:
np.random.randint(10, 20, size=10)

array([17, 17, 12, 15, 10, 10, 18, 13, 16, 13])

In [28]:
prices = []
price = 10000
for i in range(250):
    tmp = price * (1 + np.random.randn(1)/100.)
    price = tmp[0]
    prices.append(price)
prices[:10]

[9854.250014680294,
 9865.853842026298,
 10039.753149275535,
 9883.985248297375,
 9864.338641314616,
 9908.894324682533,
 9960.580376765703,
 10048.107820921025,
 10062.070408586109,
 10086.915779784158]

### 정수 데이터 카운팅

In [29]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [30]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [31]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [32]:
count

array([2, 2, 1], dtype=int64)

In [33]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6)

array([0, 2, 3, 1, 0, 0], dtype=int64)