# 벡터와 벡터의 곱셈

In [1]:
import numpy as np

In [2]:
x = np.arange(1, 4).reshape(3, 1)
y = np.arange(4, 7).reshape(3, 1)
x, y

(array([[1],
        [2],
        [3]]),
 array([[4],
        [5],
        [6]]))

In [3]:
x.shape, y.shape

((3, 1), (3, 1))

In [4]:
x.T.shape

(1, 3)

In [5]:
z = x.T @ y
z

array([[32]])

In [6]:
z.shape

(1, 1)

In [7]:
z[0, 0]

32

In [8]:
x = np.arange(1, 7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
x @ x.T

array([[14, 32],
       [32, 77]])

### 가중합 (복수의 데이터 각각의 수에 어떤 가중치를 곱한 후 그 결과들을 다시 합한 것)

In [14]:
p = np.array([100, 80, 50])
n = np.array([3, 4, 5]).reshape(3, 1)
money = p @ n
print(f'가격: 100 x 3 + 80 x 4 + 50 x 5 = {money[0]}')

가격: 100 x 3 + 80 x 4 + 50 x 5 = 870


### 연습문제 2.2.4