In [1]:
import numpy as np

### 연습 문제 1

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 연습 문제 2

In [16]:
a = np.hstack([np.zeros(4), np.ones(1), np.zeros(5)])
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### 연습 문제 3

In [4]:
b = np.arange(10, 50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 연습 문제 4

In [5]:
c = np.flip(b)
c

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### 연습 문제 5

In [7]:
d = np.arange(9)
d = d.reshape(3, 3)
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 연습 문제 6

In [9]:
v = np.array([1, 2, 0, 0, 4, 0])
v[v * 1 != 0]

array([1, 2, 4])

### 연습 문제 7

In [10]:
np.identity(n=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 연습 문제 8

In [13]:
r = np.random.rand(9).reshape(3, 3)
r

array([[0.76398734, 0.39552135, 0.7893277 ],
       [0.99209351, 0.64224366, 0.22514932],
       [0.13056396, 0.20950574, 0.2319395 ]])

### 연습 문제 9

In [14]:
maxi = r.max()
mini = r.min()
print(f'최댓값 원소: {maxi}, 최솟값 원소: {mini}')

최댓값 원소: 0.9920935120637562, 최솟값 원소: 0.1305639623342455


### 연습 문제 10

In [15]:
r_mean = r.mean(axis=1)
c_mean = r.mean(axis=0)
print(f'행의 평균: {r_mean}, 열의 평균: {c_mean}')

행의 평균: [0.64961213 0.61982883 0.19066973], 열의 평균: [0.6288816  0.41575691 0.41547217]
